require('mini.indentscope').setup()
require('mini.comment').setup()
require('mini.pairs').setup()
require('mini.surround').setup()
require('mini.move').setup()
require('mini.starter').setup()
require('mini.tabline').setup()
require('mini.statusline').setup()
